(lang dune 3.24)

(name interstellar-traveler)

(generate_opam_files true)

(source
 (github Eric2422/interstellar-traveler))

(authors "Eric Zhang <ericbkzhang@gmail.com>")

(maintainers "Eric Zhang <ericbkzhang@gmail.com>")

(license MIT)

(documentation https://url/to/documentation)

(package
 (name interstellar-traveler)
 (synopsis "Relativity in OCaml, because why not?")
 (description "Calculations of space and time dilation for an interstellar traveler.")
 (depends ocaml)
 (tags
  ("physics")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
